version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: dc-gall-guard-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=dcinside-watchdog
    restart: unless-stopped

  dc-gall-guard:
    build: .
    container_name: dc-gall-guard
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/dcinside-watchdog
      - TARGET_GALLERY_IDS=${TARGET_GALLERY_IDS:-programming}
      - CRON_EXPR=${CRON_EXPR:-*/15 * * * *}
      - CRAWL_PAGES=${CRAWL_PAGES:-1}
      - Z_SCORE_THRESHOLD=${Z_SCORE_THRESHOLD:-3}
      - MIN_REC_CHANGE=${MIN_REC_CHANGE:-5}
      - API_PORT=${API_PORT:-3000}
      - API_KEY=${API_KEY}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
    restart: unless-stopped

volumes:
  mongodb_data:
